apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-configmap
  namespace: hackaton
  labels:
    app: cm-postgres
data:
  DB_HOST: "postgres-service"
  DB_NAME: "videos"
  DB_USER: "admin"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
  AWS_SQS_QUEUE_NAME: "video-queue"
  AWS_S3_BUCKET: "videos"
  AWS_S3_ENDPOINT: "http://localstack:4566"
  AWS_SQS_ENDPOINT: "http://localstack:4566"
  APP_DOWNLOAD_URL: "http://controller:8080/controller/v1/download/"
  AWS_S3_FORCE_PATH_STYLE: "true"
