apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: controllerr-hpa
  namespace: hackaton
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: controllerr-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80