apiVersion: v1
kind: Service
metadata:
  name: controller-service
  namespace: hackaton
spec:
  selector:
    app: ds-controller
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer