spring:
  profiles:
    active: ${springProfile:local}
  application:
    name: processor
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
#  main:
#    lazy-initialization: true
#  devtools:
#    restart:
#      enabled: false

server:
  servlet:
    context-path: /processor
  port: 8081

management:
    endpoints:
      web:
        exposure:
            include: "*"
    endpoint:
      health:
        show-details: always
