spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      sqs: {}
      s3:
        path-style-access-enabled: false
      ses: {}

aws:
  queue:
    video-queue: ${AWS_SQS_QUEUE_NAME}
  s3:
    bucket: ${AWS_S3_BUCKET}
    video-bucket: ${AWS_S3_BUCKET}
  ses:
    email-from: ${AWS_SES_EMAIL_FROM}

app:
  download-url: ${APP_DOWNLOAD_URL}