spring:
  profiles:
    active: ${springProfile:local}
  application:
    name: processor
  datasource:
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /processor
  port: 8081

management:
    endpoints:
      web:
        exposure:
            include: "*"
    endpoint:
      health:
        show-details: always
