apiVersion: v1
kind: ConfigMap
metadata:
  name: processor-configmap
  namespace: hackaton
  labels:
    app: cm-postgres
data:
  DB_HOST: "postgres-service"
  DB_NAME: "videos"
  DB_USER: "admin"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
  AWS_SQS_QUEUE_NAME: "video-queue"
  AWS_S3_BUCKET: "videos"
  AWS_SES_EMAIL_FROM: "tiagogn@gmail.com"
  AWS_SQS_ENDPOINT: "http://localstack:4566"
  AWS_S3_ENDPOINT: "http://localstack:4566"
  AWS_SES_ENDPOINT: "http://localstack:4566"
  AWS_S3_FORCE_PATH_STYLE: "true"

