apiVersion: v1
kind: Service
metadata:
  name: processor-service
  namespace: hackaton
spec:
  selector:
    app: ds-processor
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer